language: perl6
sudo: true
dist: trusty
before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -qq -y liblmdb-dev
    - rakudobrew build zef
    - zef install File::Temp
perl6:
    - latest
